# Generated by Django 4.2.11 on 2024-08-30 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Opis projektu')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
            ],
            options={
                'verbose_name_plural': 'Wizyty',
            },
        ),
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('content', models.CharField(max_length=1000, verbose_name='Opis')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
                ('image', models.ImageField(blank=True, null=True, upload_to='realizations_images/', verbose_name='Zdjęcie główne')),
            ],
            options={
                'verbose_name_plural': 'Realizacje',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RealizationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realizations_images/')),
                ('realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.realization')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor komentarza')),
                ('realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.realization', verbose_name='Realizacja')),
            ],
            options={
                'verbose_name_plural': 'Komentarze',
                'ordering': ['-date'],
            },
        ),
    ]
