# Generated by Django 4.2.11 on 2024-05-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='appointment',
        ),
    ]
