# Generated by Django 4.2.11 on 2024-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
