# Generated by Django 4.2.11 on 2024-05-28 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_appointment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 10, 16, 18, 421503, tzinfo=datetime.timezone.utc), verbose_name='Data dodania'),
        ),
    ]
