# Generated by Django 4.2.11 on 2024-05-30 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_realization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 17, 46, 367460, tzinfo=datetime.timezone.utc), verbose_name='Data dodania'),
        ),
    ]
