# Generated by Django 4.2.11 on 2024-06-11 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_realization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 14, 5, 18, 522426, tzinfo=datetime.timezone.utc), verbose_name='Data dodania'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
