# Generated by Django 4.2.11 on 2024-06-11 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_realization_date_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 17, 2, 9, 73715, tzinfo=datetime.timezone.utc), verbose_name='Data dodania'),
        ),
    ]
