# Generated by Django 4.2.11 on 2024-06-14 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_realization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 12, 21, 19, 578028, tzinfo=datetime.timezone.utc), verbose_name='Data dodania'),
        ),
    ]
