# Generated by Django 4.2.11 on 2024-06-14 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_realization_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realization',
            options={'ordering': ['date'], 'verbose_name_plural': 'Realizacje'},
        ),
        migrations.AlterField(
            model_name='realization',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
    ]
