# Generated by Django 4.2.11 on 2024-06-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_realization_image_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='realization',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Realizacje'},
        ),
        migrations.AlterField(
            model_name='realization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Zdjęcie'),
        ),
    ]
