# Generated by Django 4.2.11 on 2024-06-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_comment_options_alter_realization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='realizations_images/', verbose_name='Zdjęcie główne'),
        ),
        migrations.CreateModel(
            name='RealizationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realizations_images/')),
                ('realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.realization')),
            ],
        ),
    ]
